spring:
  profiles:
    active: @profileActive@
#    active: dev

---

server:
  port: 8090
  servlet:
    context-path: /english-web
spring:
  profiles: dev
  application:
    name: english-provider
  datasource:

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.22.131:3306/english_test?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: english
    password: english
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 50
      validation-query: SELECT 1
      test-while-idle: true
      aop-patterns: com.tfjybj.physical.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
  #redis
  redis:
    host: 192.168.22.64
    port: 6379
    password:
    database: 1
    timeout: 300000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    mapUnderscoreToCamelCase: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: ID_WORKER_STR

#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

##xxl-job
xxl:
  job:
    admin:
      addresses: http://192.168.22.67:8080/xxl-job-admin
    executor:
      appname: demo-job
      ip:
      port: 9998
      logpath: /data/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

# fastdfs
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list: 192.168.22.64:22122
  replace-ip:
    source: 192.168.22.64
    dest: 192.168.22.64
    #pool:
    #jmx-enabled:false

---

server:
  port: 8090
  servlet:
    context-path: /english-web
spring:
  profiles: prod
  application:
    name: english-provider
  datasource:

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.22.59:3306/english_prod?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: english
    password: english
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 50
      validation-query: SELECT 1
      test-while-idle: true
      aop-patterns: com.tfjybj.physical.*
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
  #redis
  redis:
    host: 192.168.22.64
    port: 6379
    password:
    database: 1
    timeout: 300000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    mapUnderscoreToCamelCase: true
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: ID_WORKER_STR

#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

##xxl-job
xxl:
  job:
    admin:
      addresses: http://192.168.22.67:8080/xxl-job-admin
    executor:
      appname: demo-job
      ip:
      port: 9998
      logpath: /data/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:

# fastdfs
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  tracker-list: 192.168.22.64:22122
  replace-ip:
    source: 192.168.22.64
    dest: 192.168.22.64
    #pool:
    #jmx-enabled:false